import { useEffect, useState } from 'react';
import TicketDetailModal from '../components/TicketDetailModal';

const API_URL = import.meta.env.VITE_SUPPORT_API_URL || 'http://localhost:8000/api/v1';

interface Ticket {
  id: string;
  customer_id: string;
  thread_id: string;
  category: string;
  description: string;
  priority: string;
  status: string;
  assigned_to: string;
  created_at: string;
  updated_at: string;
}

const Tickets = () => {
  const [tickets, setTickets] = useState<Ticket[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedTicket, setSelectedTicket] = useState<Ticket | null>(null);

  useEffect(() => {
    const fetchTickets = async () => {
      try {
        const res = await fetch(`${API_URL}/tickets`);
        const data = await res.json();
        setTickets(data.tickets || []);
      } catch (error) {
        console.error("Failed to fetch tickets:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchTickets();
  }, []);

  return (
    <div>
      <h1>Support Tickets</h1>
      <p className="page-description">
        Manage customer support tickets generated by the AI system or escalated by users.
      </p>

      <div className="table-container">
        {loading ? (
          <div style={{ padding: '2rem', textAlign: 'center' }}>Loading...</div>
        ) : (
          <table>
            <thead>
              <tr>
                <th>Status</th>
                <th>Priority</th>
                <th>Category</th>
                <th>Description</th>
                <th>Created</th>
              </tr>
            </thead>
            <tbody>
              {tickets.length === 0 ? (
                <tr>
                  <td colSpan={5} style={{ textAlign: 'center', padding: '2rem' }}>
                    No tickets found.
                  </td>
                </tr>
              ) : (
                tickets.map(t => (
                  <tr key={t.id} onClick={() => setSelectedTicket(t)} style={{ cursor: 'pointer' }}>
                    <td>
                      <span className={`badge ${t.status === 'open' ? 'warning' : 'low'}`}>
                        {t.status}
                      </span>
                    </td>
                    <td>
                      <span className={`badge ${t.priority}`}>
                        {t.priority}
                      </span>
                    </td>
                    <td>{t.category}</td>
                    <td style={{ maxWidth: '300px', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                      {t.description}
                    </td>
                    <td>{new Date(t.created_at).toLocaleString()}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        )}
      </div>

      {selectedTicket && (
        <TicketDetailModal ticket={selectedTicket} onClose={() => setSelectedTicket(null)} />
      )}
    </div>
  );
};

export default Tickets;
