"""make support_tickets customer_id nullable

Revision ID: f5b5cf38a6d2
Revises: c48e7c309cd8
Create Date: 2026-07-21 09:01:45.031673
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f5b5cf38a6d2'
down_revision: Union[str, None] = 'c48e7c309cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_tickets', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_tickets', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
